import {
  Activity,
  ArrowDownRight,
  ArrowUpRight,
  BadgeCheck,
  Banknote,
  Bell,
  Boxes,
  Building2,
  CircleDollarSign,
  CreditCard,
  Gauge,
  LifeBuoy,
  LineChart,
  LockKeyhole,
  MessageSquare,
  PieChart,
  Receipt,
  Settings,
  ShieldCheck,
  Sparkles,
  Users,
  Zap,
} from "lucide-react";

export type Locale = "es" | "en";
export type SectionId = "overview" | "revenue" | "customers" | "subscriptions" | "workflows" | "reports" | "settings";
export type CustomerStatus = "healthy" | "expansion" | "atRisk" | "onboarding";
export type SortKey = "arr" | "seats" | "renewalDate";
export type Trend = "up" | "down" | "neutral";

export const navItems = [
  { id: "overview", icon: Gauge },
  { id: "revenue", icon: LineChart },
  { id: "customers", icon: Users },
  { id: "subscriptions", icon: CreditCard },
  { id: "workflows", icon: Zap },
  { id: "reports", icon: PieChart },
  { id: "settings", icon: Settings },
] as const;

export const secondaryNavItems = [
  { id: "security", icon: ShieldCheck },
  { id: "support", icon: LifeBuoy },
] as const;

export const metricItems = [
  { id: "netRevenue", value: "$284.6K", change: "+18.4%", trend: "up", icon: CircleDollarSign },
  { id: "activeCustomers", value: "8,492", change: "+642", trend: "up", icon: Building2 },
  { id: "churnRisk", value: "2.8%", change: "-0.9%", trend: "down", icon: Activity },
  { id: "openInvoices", value: "$38.2K", change: "+6", trend: "neutral", icon: Receipt },
] as const;

export const revenueSeries = [
  { month: "jan", revenue: 112, expansion: 28 },
  { month: "feb", revenue: 128, expansion: 35 },
  { month: "mar", revenue: 141, expansion: 42 },
  { month: "apr", revenue: 156, expansion: 51 },
  { month: "may", revenue: 173, expansion: 58 },
  { month: "jun", revenue: 190, expansion: 63 },
  { month: "jul", revenue: 208, expansion: 69 },
  { month: "aug", revenue: 225, expansion: 74 },
  { month: "sep", revenue: 241, expansion: 82 },
  { month: "oct", revenue: 260, expansion: 86 },
  { month: "nov", revenue: 276, expansion: 91 },
  { month: "dec", revenue: 292, expansion: 98 },
] as const;

export const customers = [
  {
    id: "northstar",
    company: "Northstar Labs",
    owner: "Maya Chen",
    plan: "Scale",
    status: "healthy",
    arr: 42800,
    seats: 84,
    renewalDate: "2026-08-14",
    usage: 91,
    region: "North America",
  },
  {
    id: "brightline",
    company: "Brightline Health",
    owner: "Elliot Park",
    plan: "Enterprise",
    status: "expansion",
    arr: 71200,
    seats: 126,
    renewalDate: "2026-09-02",
    usage: 96,
    region: "North America",
  },
  {
    id: "aster",
    company: "Aster Fintech",
    owner: "Nora Silva",
    plan: "Scale",
    status: "atRisk",
    arr: 28400,
    seats: 52,
    renewalDate: "2026-06-26",
    usage: 64,
    region: "LATAM",
  },
  {
    id: "orbit",
    company: "Orbit Supply",
    owner: "Theo Grant",
    plan: "Growth",
    status: "onboarding",
    arr: 18900,
    seats: 31,
    renewalDate: "2026-10-19",
    usage: 73,
    region: "Europe",
  },
  {
    id: "helio",
    company: "Helio Works",
    owner: "Priya Raman",
    plan: "Enterprise",
    status: "healthy",
    arr: 96500,
    seats: 212,
    renewalDate: "2026-12-07",
    usage: 98,
    region: "APAC",
  },
] as const;

export const activityItems = [
  { id: "renewalApproved", timeAgo: "12m", icon: BadgeCheck, color: "text-mint" },
  { id: "usageAlert", timeAgo: "48m", icon: Bell, color: "text-amberline" },
  { id: "billingWorkflow", timeAgo: "2h", icon: Banknote, color: "text-pulse-500" },
  { id: "feedbackCaptured", timeAgo: "4h", icon: MessageSquare, color: "text-coral" },
] as const;

export const segments = [
  { id: "enterprise", value: 48, color: "bg-pulse-500" },
  { id: "scale", value: 34, color: "bg-mint" },
  { id: "growth", value: 18, color: "bg-amberline" },
] as const;

export const pipelineItems = [
  { id: "qualified", value: "$182K", icon: Sparkles },
  { id: "procurement", value: "$96K", icon: LockKeyhole },
  { id: "launched", value: "$74K", icon: Boxes },
] as const;

export const trendIcons = {
  up: ArrowUpRight,
  down: ArrowDownRight,
  neutral: ArrowUpRight,
} as const;

export const dictionary = {
  es: {
    app: {
      console: "Consola de ingresos",
      workspace: "Espacio Helio",
      searchPlaceholder: "Buscar clientes, facturas, automatizaciones",
      automations: "Automatizaciones",
      openMenu: "Abrir menú",
      closeMenu: "Cerrar menú",
      notifications: "Notificaciones",
      profile: "Perfil",
      language: "Idioma",
      liveHealth: "Salud del espacio en vivo",
      title: "Centro de comando PulseFlow",
      description: "Monitorea ingresos, retención, salud de clientes y actividad operativa en PulseFlow.",
      export: "Exportar",
      createWorkflow: "Crear automatización",
      collapseSidebar: "Colapsar barra lateral",
      expandSidebar: "Expandir barra lateral",
      logout: "Cerrar sesion",
    },
    nav: {
      overview: "Resumen",
      revenue: "Ingresos",
      customers: "Clientes",
      subscriptions: "Suscripciones",
      workflows: "Automatizaciones",
      reports: "Reportes",
      settings: "Ajustes",
      security: "Seguridad",
      support: "Soporte",
    },
    sections: {
      overview: {
        title: "Resumen operativo",
        body: "Vista ejecutiva con métricas, movimiento de ingresos, actividad y cuentas prioritarias.",
      },
      revenue: {
        title: "Ingresos",
        body: "Analiza ARR base, expansión y señales de renovación por segmento.",
      },
      customers: {
        title: "Clientes",
        body: "Gestiona cuentas, riesgo, propietarios y oportunidades de expansión.",
      },
      subscriptions: {
        title: "Suscripciones",
        body: "Controla planes, renovaciones, facturación abierta y contratos activos.",
      },
      workflows: {
        title: "Automatizaciones",
        body: "Orquesta tareas recurrentes para onboarding, cobranzas y alertas de éxito.",
      },
      reports: {
        title: "Reportes",
        body: "Prepara reportes ejecutivos con salud, retención e ingresos proyectados.",
      },
      settings: {
        title: "Ajustes",
        body: "Configura preferencias, permisos, idioma, seguridad y notificaciones.",
      },
    },
    metrics: {
      netRevenue: { label: "Ingresos netos", detail: "vs. mes anterior" },
      activeCustomers: { label: "Clientes activos", detail: "nuevos usuarios agregados" },
      churnRisk: { label: "Riesgo de churn", detail: "salud de cuentas mejorada" },
      openInvoices: { label: "Facturas abiertas", detail: "requieren seguimiento" },
    },
    chart: {
      title: "Impulso de ingresos",
      description: "ARR, expansión e ingresos retenidos por mes",
      baseArr: "ARR base",
      expansion: "Expansión",
      revenueMix: "Mix de ingresos",
      revenueMixDetail: "ARR por segmento de cliente",
      expansionPipeline: "Pipeline de expansión",
    },
    months: {
      jan: "Ene",
      feb: "Feb",
      mar: "Mar",
      apr: "Abr",
      may: "May",
      jun: "Jun",
      jul: "Jul",
      aug: "Ago",
      sep: "Sep",
      oct: "Oct",
      nov: "Nov",
      dec: "Dic",
    },
    table: {
      title: "Gestión de clientes",
      description: "Cuentas prioritarias para ingresos y éxito del cliente",
      search: "Buscar clientes",
      filter: "Filtro",
      allStatuses: "Todos los estados",
      sortBy: "Ordenar por",
      columns: {
        company: "Empresa",
        owner: "Responsable",
        plan: "Plan",
        status: "Estado",
        arr: "ARR",
        seats: "Usuarios",
        renewal: "Renovación",
        action: "Acción",
      },
      viewDetails: "Ver detalle",
      addCustomer: "Agregar cliente",
      editStatus: "Editar estado",
      deleteCustomer: "Eliminar",
      empty: "No hay clientes que coincidan con la búsqueda.",
    },
    statuses: {
      healthy: "Saludable",
      expansion: "Expansión",
      atRisk: "En riesgo",
      onboarding: "Onboarding",
    },
    sort: {
      arr: "ARR",
      seats: "Usuarios",
      renewalDate: "Renovación",
    },
    activity: {
      title: "Actividad",
      description: "Señales en vivo desde automatizaciones de ingresos",
      renewalApproved: {
        title: "Renovación enterprise aprobada",
        description: "Helio Works firmó una renovación de 24 meses con pago anual anticipado.",
      },
      usageAlert: {
        title: "Alerta de uso resuelta",
        description: "El volumen de automatizaciones de Aster Fintech volvió bajo el umbral.",
      },
      billingWorkflow: {
        title: "Automatización de facturación iniciada",
        description: "Northstar Labs activó aprobaciones financieras para facturas.",
      },
      feedbackCaptured: {
        title: "Feedback de cliente capturado",
        description: "Brightline Health pidió reportes por cohortes para equipos de atención.",
      },
    },
    segments: {
      enterprise: "Enterprise",
      scale: "Scale",
      growth: "Growth",
    },
    pipeline: {
      qualified: "Calificado",
      procurement: "Compras",
      launched: "Lanzado",
    },
    modal: {
      close: "Cerrar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      workflowTitle: "Crear automatización",
      workflowDescription: "Simula una automatización operativa lista para activar en PulseFlow.",
      workflowName: "Nombre de la automatización",
      workflowNamePlaceholder: "Alerta de renovación crítica",
      trigger: "Disparador",
      triggerPlaceholder: "Renovación a menos de 30 días",
      create: "Crear automatización",
      customerTitle: "Detalle de cliente",
      customerDescription: "Resumen de cuenta, uso y próximos pasos.",
      exportTitle: "Exportar reporte",
      exportDescription: "Elige el formato para simular una descarga del dashboard.",
      exportCsv: "CSV",
      exportPdf: "PDF",
      exportDone: "Exportación preparada",
      download: "Simular descarga",
      addCustomerTitle: "Agregar cliente",
      addCustomerDescription: "Crea una cuenta mock para probar la interacción local del dashboard.",
      company: "Empresa",
      owner: "Responsable",
      plan: "Plan",
      arr: "ARR",
      seats: "Usuarios",
      renewalDate: "Fecha de renovacion",
      region: "Region",
      add: "Agregar",
    },
    details: {
      annualRevenue: "Ingreso anual",
      seats: "Usuarios",
      usage: "Uso",
      region: "Región",
      owner: "Responsable",
      nextRenewal: "Próxima renovación",
    },
    settings: {
      title: "Preferencias del espacio",
      language: "Idioma",
      theme: "Tema",
      notifications: "Notificaciones",
      security: "Seguridad",
      enabled: "Activado",
      enterpriseSso: "SSO enterprise",
      dataRetention: "Retención de datos",
    },
    toast: {
      workflowCreated: "Automatización creada correctamente",
      customerAdded: "Cliente agregado",
      customerRemoved: "Cliente eliminado",
      exportReady: "Reporte listo para descargar",
      openedCustomer: "Detalle de cliente abierto",
      sectionChanged: "Sección actualizada",
      notificationsRead: "Notificaciones revisadas",
      languageChanged: "Idioma actualizado",
      welcome: "Bienvenido a PulseFlow",
    },
    login: {
      title: "Ingresar a PulseFlow",
      subtitle: "Usa las credenciales demo o cualquier email valido para entrar.",
      email: "Email",
      password: "Contraseña",
      emailPlaceholder: "demo@pulseflow.app",
      passwordPlaceholder: "password123",
      submit: "Ingresar a la demo",
      hint: "Autenticacion mock, sin backend.",
      loading: "Ingresando...",
      demoCredentials: "Credenciales demo",
      emailRequired: "Ingresa un email.",
      emailInvalid: "Ingresa un email valido.",
      passwordRequired: "Ingresa una contraseña.",
      passwordMin: "La contraseña debe tener al menos 6 caracteres.",
    },
  },
  en: {
    app: {
      console: "Revenue console",
      workspace: "Helio workspace",
      searchPlaceholder: "Search customers, invoices, workflows",
      automations: "Automations",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      notifications: "Notifications",
      profile: "Profile",
      language: "Language",
      liveHealth: "Live workspace health",
      title: "PulseFlow command center",
      description: "Monitor revenue, retention, customer health, and operational activity across PulseFlow.",
      export: "Export",
      createWorkflow: "Create workflow",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      logout: "Log out",
    },
    nav: {
      overview: "Overview",
      revenue: "Revenue",
      customers: "Customers",
      subscriptions: "Subscriptions",
      workflows: "Workflows",
      reports: "Reports",
      settings: "Settings",
      security: "Security",
      support: "Support",
    },
    sections: {
      overview: {
        title: "Operational overview",
        body: "Executive view with metrics, revenue movement, activity, and priority accounts.",
      },
      revenue: {
        title: "Revenue",
        body: "Analyze base ARR, expansion, and renewal signals by segment.",
      },
      customers: {
        title: "Customers",
        body: "Manage accounts, risk, owners, and expansion opportunities.",
      },
      subscriptions: {
        title: "Subscriptions",
        body: "Track plans, renewals, open billing, and active contracts.",
      },
      workflows: {
        title: "Workflows",
        body: "Orchestrate automations for onboarding, collections, and success alerts.",
      },
      reports: {
        title: "Reports",
        body: "Prepare executive reports with health, retention, and projected revenue.",
      },
      settings: {
        title: "Settings",
        body: "Configure preferences, permissions, language, security, and notifications.",
      },
    },
    metrics: {
      netRevenue: { label: "Net revenue", detail: "vs. last month" },
      activeCustomers: { label: "Active customers", detail: "new seats added" },
      churnRisk: { label: "Churn risk", detail: "health score improved" },
      openInvoices: { label: "Open invoices", detail: "requires follow-up" },
    },
    chart: {
      title: "Revenue momentum",
      description: "ARR, expansion, and retained revenue by month",
      baseArr: "Base ARR",
      expansion: "Expansion",
      revenueMix: "Revenue mix",
      revenueMixDetail: "ARR by customer segment",
      expansionPipeline: "Expansion pipeline",
    },
    months: {
      jan: "Jan",
      feb: "Feb",
      mar: "Mar",
      apr: "Apr",
      may: "May",
      jun: "Jun",
      jul: "Jul",
      aug: "Aug",
      sep: "Sep",
      oct: "Oct",
      nov: "Nov",
      dec: "Dec",
    },
    table: {
      title: "Customer management",
      description: "Priority accounts for revenue and customer success teams",
      search: "Search customers",
      filter: "Filter",
      allStatuses: "All statuses",
      sortBy: "Sort by",
      columns: {
        company: "Company",
        owner: "Owner",
        plan: "Plan",
        status: "Status",
        arr: "ARR",
        seats: "Seats",
        renewal: "Renewal",
        action: "Action",
      },
      viewDetails: "View details",
      addCustomer: "Add customer",
      editStatus: "Edit status",
      deleteCustomer: "Delete",
      empty: "No customers match the current search.",
    },
    statuses: {
      healthy: "Healthy",
      expansion: "Expansion",
      atRisk: "At risk",
      onboarding: "Onboarding",
    },
    sort: {
      arr: "ARR",
      seats: "Seats",
      renewalDate: "Renewal",
    },
    activity: {
      title: "Activity feed",
      description: "Live signals from revenue workflows",
      renewalApproved: {
        title: "Enterprise renewal approved",
        description: "Helio Works signed a 24-month renewal with annual prepay.",
      },
      usageAlert: {
        title: "Usage alert resolved",
        description: "Aster Fintech automation volume returned below threshold.",
      },
      billingWorkflow: {
        title: "Billing workflow launched",
        description: "Northstar Labs enabled invoice routing for finance approvals.",
      },
      feedbackCaptured: {
        title: "Customer feedback captured",
        description: "Brightline Health requested cohort reporting for care teams.",
      },
    },
    segments: {
      enterprise: "Enterprise",
      scale: "Scale",
      growth: "Growth",
    },
    pipeline: {
      qualified: "Qualified",
      procurement: "Procurement",
      launched: "Launched",
    },
    modal: {
      close: "Close",
      cancel: "Cancel",
      confirm: "Confirm",
      workflowTitle: "Create workflow",
      workflowDescription: "Simulate an operational workflow ready to activate in PulseFlow.",
      workflowName: "Workflow name",
      workflowNamePlaceholder: "Critical renewal alert",
      trigger: "Trigger",
      triggerPlaceholder: "Renewal is less than 30 days away",
      create: "Create workflow",
      customerTitle: "Customer details",
      customerDescription: "Account summary, usage, and next steps.",
      exportTitle: "Export report",
      exportDescription: "Choose a format to simulate a dashboard download.",
      exportCsv: "CSV",
      exportPdf: "PDF",
      exportDone: "Export prepared",
      download: "Simulate download",
      addCustomerTitle: "Add customer",
      addCustomerDescription: "Create a mock account to test the dashboard's local flow.",
      company: "Company",
      owner: "Owner",
      plan: "Plan",
      arr: "ARR",
      seats: "Seats",
      renewalDate: "Renewal date",
      region: "Region",
      add: "Add",
    },
    details: {
      annualRevenue: "Annual revenue",
      seats: "Seats",
      usage: "Usage",
      region: "Region",
      owner: "Owner",
      nextRenewal: "Next renewal",
    },
    settings: {
      title: "Workspace preferences",
      language: "Language",
      theme: "Theme",
      notifications: "Notifications",
      security: "Security",
      enabled: "Enabled",
      enterpriseSso: "Enterprise SSO",
      dataRetention: "Data retention",
    },
    toast: {
      workflowCreated: "Workflow created successfully",
      customerAdded: "Customer added",
      customerRemoved: "Customer removed",
      exportReady: "Report ready to download",
      openedCustomer: "Customer details opened",
      sectionChanged: "Section updated",
      notificationsRead: "Notifications reviewed",
      languageChanged: "Language updated",
      welcome: "Welcome to PulseFlow",
    },
    login: {
      title: "Sign in to PulseFlow",
      subtitle: "Use the demo credentials or any valid email to enter.",
      email: "Email",
      password: "Password",
      emailPlaceholder: "demo@pulseflow.app",
      passwordPlaceholder: "password123",
      submit: "Enter demo",
      hint: "Mock authentication, no backend.",
      loading: "Signing in...",
      demoCredentials: "Demo credentials",
      emailRequired: "Enter an email.",
      emailInvalid: "Enter a valid email.",
      passwordRequired: "Enter a password.",
      passwordMin: "Password must be at least 6 characters.",
    },
  },
} as const;
